### ISSUE TITLE
Inherited class is lost while deserialization.

### ISSUE THREAD

**Issue by Titounnosaure** [ramonhagenaars/jsons#35] opened 2019-03-30 09:31 UTC
Inherited class is lost while deserialization. In the example below, the object chmsg3 is serialized as a class ChatMessageSection with the weight attribute  ('weight': 17, '-cls': '__main__.ChatMessageSection'}]). But after deserialization the object becomes a ChatMessage.

```python
import jsons
from dataclasses import dataclass
from typing import List

@dataclass
class ChatUser:
    name: str

@dataclass
class ChatMessage:
    user: ChatUser
    msg_text: str

@dataclass
class ChatMessageSection(ChatMessage):
    weight: int

@dataclass
class ChatMessages:
    msg_list: List[ChatMessage]

chmsg = ChatMessage(ChatUser("Thierry"), "Bonjour")
chmsg2 = ChatMessage(ChatUser("Casimir"), "Hello")
chmsg3 = ChatMessageSection(ChatUser("Leonard"), "Coucou", weight=17)
chat_msgs = ChatMessages([chmsg, chmsg2, chmsg3])

print(chat_msgs, end="\n\n")
dumped = jsons.dump(chat_msgs, strip_microseconds=True, verbose=jsons.Verbosity.WITH_EVERYTHING)
print(dumped, end="\n\n")
instance = jsons.load(dumped)
print(instance, end="\n\n")
```

**Comment by ramonhagenaars** [comment] 2019-03-31 11:46
This is actually a bug. It was caused by ``jsons`` not handling verbose dumps in combination with lists. It will be fixed in version ``0.8.3`` which is to be deployed today.

**Comment by ramonhagenaars** [comment] 2019-03-31 13:06
This bug has been solved in [0.8.3](https://pypi.org/project/jsons/).

**Closed by ramonhagenaars** 2019-03-31 13:06 UTC
Labels: bug, in progress

**Comment by Titounnosaure** [comment] 2019-04-01 05:46
Thank you. Works fine with the new release 0.8.3.

**Comment by ramonhagenaars** [comment] 2019-04-01 06:26
Great! 😃
